# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Cypress

on: pull_request

permissions:
  contents: read

concurrency:
  group: cypress-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: ${{ github.event.repository.name }}
  CYPRESS_baseUrl: http://localhost:8081/index.php

jobs:
  changes:
    runs-on: ubuntu-latest-low

    outputs:
      src: ${{ steps.changes.outputs.src}}

    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - 'appinfo/**'
              - 'lib/**'
              - 'src/**'
              - 'templates/**'
              - 'babel.config.js'
              - 'composer.json'
              - 'composer.lock'
              - 'cypress.config.js'
              - 'package.json'
              - 'package-lock.json'
              - 'tsconfig.json'
              - '**.js'
              - '**.ts'
              - '**.vue'

  cypress:
    runs-on: ubuntu-latest

    needs: changes

    strategy:
      fail-fast: false
      matrix:
        node-version: [22]
        php-versions: ['8.2']
        databases: ['sqlite']
        server-versions: ['stable30', 'master']

    env:
      PUPPETEER_SKIP_DOWNLOAD: true

    steps:
      - name: Disabled on forks
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: |
          echo 'Can not approve PRs from forks'
          exit 1

      - name: Checkout server
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout app
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2
        with:
          php-version: ${{ matrix.php-versions }}
            # https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        with:
          fallbackNode: "^20"
          fallbackNpm: "^10"
          path: apps/${{ env.APP_NAME }}

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g 'npm@${{ steps.versions.outputs.npmVersion }}'

      - name: Install node dependencies & build app
        working-directory: apps/${{ env.APP_NAME }}
        run: |
          npm ci
          TESTING=true npm run build --if-present

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          ./occ app:enable --force ${{ env.APP_NAME }}

      - name: Run Nextcloud
        run: php -S 0.0.0.0:8081 &

      - name: Run E2E cypress tests
        run: |
          cd 'apps/${{ env.APP_NAME }}'
          npx wait-on $CYPRESS_baseUrl
          npx cypress run --record false --config defaultCommandTimeout=20000,video=false
        env:
          CYPRESS_ncVersion: ${{ matrix.server-versions }}

      - name: Upload test failure screenshots
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: failure()
        with:
          name: screenshots_${{ matrix.server-versions }}
          path: apps/${{ env.APP_NAME }}/cypress/screenshots/
          retention-days: 5

      - name: Upload NC logs
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: failure()
        with:
          name: nc_logs_${{ matrix.server-versions }}.log
          path: data/nextcloud.log
          retention-days: 5

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: [changes, cypress]

    if: always()

    name: cypress-summary

    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src != 'false' && needs.cypress.result != 'success' }}; then exit 1; fi
